list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Math/Math.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Math/Geometry/AABB2.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Math/Geometry/AABB3.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Math/Geometry/Circle.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Math/Geometry/MatrixUtil.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Math/Geometry/Plane.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Math/Geometry/Ray3.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Math/Geometry/Sphere.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Utils/Convert.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Utils/StringUtils.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Utils/Env.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Utils/Dialog.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Utils/Timer.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Utils/AppSettings.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Utils/AppLogic.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Utils/FramerateSmoother.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Utils/Json/SimpleJson.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Utils/File/Execute.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Utils/File/FileLoader.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Utils/File/Logfile.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Utils/File/FileUtils.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Utils/File/LineReader.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Utils/File/CsvWriter.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Utils/File/PathWatch.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Utils/Events/EventManager.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Utils/Events/Stream/BinaryStream.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Utils/Events/Stream/StringStream.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Utils/Mesh/IndexMesh.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Utils/Mesh/MeshSmoothing.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Utils/Mesh/TriangleNormals.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Utils/Parallel/Histogram.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Utils/Parallel/Reduction.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Utils/Regex/Tokens.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Utils/Regex/TransformString.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Utils/SciVis/CameraPath.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Utils/SciVis/ImportanceCriteria.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Utils/SciVis/SciVisApp.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Utils/SciVis/Navigation/CameraNavigator2D.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Utils/SciVis/Navigation/FirstPersonNavigator.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Utils/SciVis/Navigation/TrackballNavigator.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Utils/SciVis/Navigation/TurntableNavigator.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Color.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Utils/HiDPI.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Utils/DeviceSelection.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Utils/InteropCompute.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Utils/InteropLevelZero.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Utils/InteropHIP.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Texture/Bitmap.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Video/VideoWriter.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Scene/Camera.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Scene/CameraHelper.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Scene/RenderTarget.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Scene/SceneNode.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/GLSL/PreprocessorGlsl.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Vulkan/libs/volk/volk.c")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Vulkan/libs/SPIRV-Reflect/spirv_reflect.c")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Vulkan/Utils/VmaImpl.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Vulkan/Utils/Memory.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Vulkan/Utils/Instance.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Vulkan/Utils/Status.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Vulkan/Utils/Device.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Vulkan/Utils/DeviceSelectionVulkan.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Vulkan/Utils/Swapchain.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Vulkan/Utils/SyncObjects.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Vulkan/Utils/Timer.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Vulkan/Utils/ScreenshotReadbackHelper.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Vulkan/Utils/DeviceThreadInfo.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Vulkan/Utils/InteropLevelZero.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Vulkan/Utils/InteropHIP.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Vulkan/Buffers/Buffer.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Vulkan/Buffers/Framebuffer.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Vulkan/Image/Image.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Vulkan/Shader/Shader.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Vulkan/Shader/ShaderManager.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Vulkan/Render/CommandBuffer.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Vulkan/Render/Pipeline.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Vulkan/Render/ComputePipeline.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Vulkan/Render/GraphicsPipeline.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Vulkan/Render/RayTracingPipeline.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Vulkan/Render/AccelerationStructure.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Vulkan/Render/Data.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Vulkan/Render/Helpers.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Vulkan/Render/Renderer.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Vulkan/Render/Passes/Pass.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Vulkan/Render/Passes/BlitComputePass.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Vulkan/Render/Passes/BlitRenderPass.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/SDL/SDLWindow.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/SDL/Input/SDLGamepad.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/SDL/Input/SDLKeyboard.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/SDL/Input/SDLMouse.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/ImGui/imgui.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/ImGui/imgui_custom.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/ImGui/imgui_demo.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/ImGui/imgui_draw.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/ImGui/imgui_stdlib.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/ImGui/imgui_tables.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/ImGui/imgui_verticaltext.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/ImGui/imgui_widgets.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/ImGui/imgui_impl_sdl3.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/ImGui/imgui_impl_vulkan.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/ImGui/ImGuiWrapper.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/ImGui/ImGuiFileDialog/CustomFont.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/ImGui/ImGuiFileDialog/ImGuiFileDialog.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/ImGui/Widgets/CheckpointWindow.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/ImGui/Widgets/ColorLegendWidget.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/ImGui/Widgets/CoordinateAxesOverlayWidget.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/ImGui/Widgets/MultiVarTransferFunctionWindow.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/ImGui/Widgets/NumberFormatting.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/ImGui/Widgets/PropertyEditor.cpp")
list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/ImGui/Widgets/TransferFunctionWindow.cpp")

find_package(CUDAToolkit QUIET)
if(${CUDAToolkit_FOUND} AND ${CUDAToolkit_VERSION} VERSION_GREATER_EQUAL "11.5")
    set(SGL_INTERFACE_COMPILE_DEFINITIONS "SUPPORT_CUDA_INTEROP")
    list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Utils/InteropCuda.cpp")
    list(APPEND SOURCES_SGL "${CMAKE_CURRENT_SOURCE_DIR}/third_party/sgl/src/Graphics/Vulkan/Utils/InteropCuda.cpp")
    set(SGL_USE_CUDA ON)
else()
    set(SGL_INTERFACE_COMPILE_DEFINITIONS "")
    set(SGL_USE_CUDA OFF)
endif()

add_library(sgl STATIC ${SOURCES_SGL})
target_include_directories(sgl PUBLIC third_party)
target_include_directories(sgl PUBLIC third_party/sgl/src)
target_include_directories(sgl PUBLIC third_party/sgl/src/Graphics/Vulkan/libs)
target_include_directories(sgl PUBLIC third_party/sgl/src/Graphics/Vulkan/libs/Vulkan-Headers)
target_include_directories(sgl PUBLIC third_party/sgl/src/Graphics/Vulkan/libs/hip/include)
target_compile_definitions(sgl PUBLIC DLL_OBJECT=)
target_compile_definitions(sgl PUBLIC USE_GLM)
target_compile_definitions(sgl PUBLIC SUPPORT_VULKAN)
target_compile_definitions(sgl PUBLIC VK_NO_PROTOTYPES)
target_compile_definitions(sgl INTERFACE USE_SGL_VULKAN_HEADERS)
target_compile_definitions(sgl PUBLIC SUPPORT_GLSLANG_BACKEND)
target_compile_definitions(sgl PUBLIC SUPPORT_TINYXML2)
target_compile_definitions(sgl PUBLIC SGL_INPUT_API_V2)
target_compile_definitions(sgl PUBLIC SUPPORT_SDL3)
target_compile_definitions(sgl PUBLIC SUPPORT_SDL)
target_compile_definitions(sgl PUBLIC SUPPORT_LEVEL_ZERO_INTEROP)
target_compile_definitions(sgl PUBLIC SUPPORT_HIP_INTEROP)
if (${SGL_USE_CUDA})
    target_compile_definitions(sgl PUBLIC SUPPORT_CUDA_INTEROP)
    target_include_directories(sgl PUBLIC ${CUDAToolkit_INCLUDE_DIRS})
endif()
if (WIN32)
    target_compile_definitions(sgl PUBLIC DISABLE_SINGLETON_BOOST_INTERPROCESS)
endif()

set(GLM_INCLUDE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/third_party/glm")
target_include_directories(sgl PUBLIC third_party/glm)
target_include_directories(sgl PUBLIC third_party/sgl/submodules/fallback)

if (WIN32)
    set(GLSLANG_SYS_NAME "Windows")
else()
    set(GLSLANG_SYS_NAME "Unix")
endif()
file(GLOB_RECURSE SOURCES_GLSLANG
        third_party/glslang/SPIRV/*.cpp
        third_party/glslang/glslang/CInterface/*.cpp
        third_party/glslang/glslang/GenericCodeGen/*.cpp
        third_party/glslang/glslang/MachineIndependent/*.cpp
        third_party/glslang/glslang/ResourceLimits/*.cpp
        third_party/glslang/glslang/OSDependent/${GLSLANG_SYS_NAME}/*.cpp)
add_library(glslang STATIC ${SOURCES_GLSLANG})
target_compile_definitions(glslang PRIVATE ENABLE_SPIRV)
target_include_directories(glslang PUBLIC third_party/glslang)
target_include_directories(glslang PUBLIC third_party/custom)
target_link_libraries(sgl PRIVATE glslang)

file(GLOB_RECURSE SOURCES_TINYXML2 third_party/tinyxml2/tinyxml2.cpp)
add_library(tinyxml2 STATIC ${SOURCES_TINYXML2})
target_include_directories(tinyxml2 PUBLIC third_party/tinyxml2)
target_link_libraries(sgl PUBLIC tinyxml2)

file(GLOB_RECURSE SOURCES_JSONCPP
        third_party/jsoncpp/src/lib_json/*.cpp)
add_library(jsoncpp STATIC ${SOURCES_JSONCPP})
target_include_directories(jsoncpp PUBLIC third_party/jsoncpp/include)
target_link_libraries(sgl PRIVATE jsoncpp)

set(BUILD_SHARED_LIBS OFF)
set(SDL_SHARED_DEFAULT OFF)
set(SDL_STATIC_DEFAULT ON)
set(SDL_DIRECTX OFF)
set(SDL_DISKAUDIO OFF)
set(SDL_RENDER_D3D OFF)
set(SDL_RENDER_D3D OFF)
set(SDL_RENDER_D3D11 OFF)
set(SDL_RENDER_D3D12 OFF)
set(SDL_RENDER_GPU OFF)
set(SDL_RENDER_VULKAN OFF)
add_subdirectory(third_party/SDL EXCLUDE_FROM_ALL)
target_link_libraries(sgl PUBLIC SDL3::SDL3-static)
